version: '3.8'

services:
  go-app:
    build: ./go-demo
    ports:
      - "8080:8080"
    environment:
      - PHP_APP_URL=https://app.kavanix.com/php
    extra_hosts:
      - "app.kavanix.com:host-gateway"
    depends_on:
      - php-app

  php-app:
    build: ./php-demo
    ports:
      - "8090:8000"
    environment:
      - APP_ENV=local
      - APP_DEBUG=true
    # Lumen default port when using php -S is usually 8000
    command: [ "php", "-S", "0.0.0.0:8000", "-t", "public" ]

  beyla:
    image: grafana/beyla:latest
    privileged: true
    pid: host
    environment:
      - BEYLA_OPEN_PORT=8080,8000
      - BEYLA_SERVICE_NAME=app-demo
      - BEYLA_TRACE_PRINTER=text
      - OTEL_EXPORTER_OTLP_ENDPOINT=http://10.11.1.68:4319
      - OTEL_EXPORTER_OTLP_HEADERS=Authorization=Basic YWRtaW46YWRtaW4=
    extra_hosts:
      - "host.docker.internal:host-gateway"
